version: "3.8"
  
services:
  web:
   image: nginx:latest
   container_name: nginx
   ports:
   - "8080:8080"
   volumes:
   - /public:/public
   - /usr/share/nginx/site.conf:/etc/nginx/conf.d/site.conf
   - /usr/share/nginx/logs:/var/log/nginx/

  php:
   image: php:7.3-fpm-alpine
   container_name: PHP7
   volumes:
   - /public:/public
   depends_on:
   - db

  db:
   image: mariadb:latest
   container_name: mariadb
   volumes:
    - /var/lib/mysql:/var/lib/mysql
   environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 1
    MYSQL_DATABASE: veeam_api
    MYSQL_USER: infiniit
    MYSQL_PASSWORD: 1nfini!t
   expose:
   - 3306

   grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose
    - 3000
