version: "3.8"
  
services:
  web:
   build: ./components/nginx/Dockerfile
   container_name: nginx
   ports:
   - 8080:8080
   volumes:
   - /public:/public
   - /usr/share/nginx/logs:/var/log/nginx/

  php:
   build: ./components/php/Dockerfile
   container_name: php
   volumes:
   - /public:/public
   depends_on:
   - db

  db:
   build: ./components/db/Dockerfile
   container_name: mariadb
   volumes:
    - /var/lib/mysql:/var/lib/mysql
   environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_DATABASE: veeam_api
    MYSQL_USER: infiniit
    MYSQL_PASSWORD: '1nfini!t'
   expose:
   - 3306

  grafana:
   image: grafana/grafana:latest
   container_name: grafana
   ports:
   - 3000:3000
