{
 "title": "Resumo de Backup",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dias", "label": "Dias", "query": "1,2,5,7,10,15,20,30" },
   {
    "name": "cliente",
    "query": "SELECT customer FROM backup_jobs"
   }
  ]
 },
 "panels": [
  {
   "title": "Dados Processados nos últimos $dias dias",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  data_processed AS \"Dados processados\"\nFROM backup_sessions\nWHERE\n  customer = \"$cliente\"\nORDER BY start_time"
    }
   ]
  },
  {
   "title": "Dados transferidos nos últimos $dias dias",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  data_transferred AS \"Dados transferidos\"\nFROM backup_sessions\nWHERE\n  customer = \"$cliente\"\nORDER BY start_time"
    }
   ]
  },
  {
   "title": "Dados transferidos $dias dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(data_transferred) as \"Dados transferidos\"\nFROM backup_sessions where customer=\"$cliente\" and start_time >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "title": "SUCESSO em $dias dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT latest_status as \"Status\"\nFROM backup_jobs where customer=\"$cliente\" and latest_status=\"Success\" and latest_run >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "title": "Dados lidos em $dias dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(data_read) as \"Dados lidos\"\nFROM backup_sessions where customer=\"$cliente\" and start_time >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "title": "FALHA em $dias dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT latest_status as \"Status\"\nFROM backup_jobs where customer=\"$cliente\" and latest_status=\"Failed\" and latest_run >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "title": "Processados em $dias dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(data_processed) as \"Dados Processados\"\nFROM backup_sessions where customer=\"$cliente\" and start_time >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "title": "ALERTA em $dias dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT latest_status as \"Status\"\nFROM backup_jobs where customer=\"$cliente\" and latest_status=\"Warning\" and latest_run >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT job_name as \"Tarefa\", avg_speed AS \"Velocidade média\", start_time as \"Início\", duration as \"Duração\", data_total as \"Total\", data_processed as \"Processado\", data_read as \"Leitura\", data_transferred as \"Transferido\", data_compress as \"Compressão\", data_dedupe as \"Deduplicação\", last_status as \"Status\"\nFROM backup_sessions where customer=\"$cliente\" and start_time >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "title": "Tempo de backup em $dias dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(duration) as \"Duração\"\nFROM backup_sessions where customer=\"$cliente\" and start_time >= now() - INTERVAL $dias DAY;"
    }
   ]
  },
  {
   "title": "Status do ultimo backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT job_name AS Rotina, latest_status AS Status, latest_run AS Data\nFROM backup_jobs where customer=\"$cliente\""
    }
   ]
  }
 ]
}